---
deployment:
  tasks:
    - export DEPLOYPATH=/home/otfidqlcuq/public_html/wp-content/plugins
    - rm -rf $DEPLOYPATH/dingconnect-recargas
    - mkdir -p $DEPLOYPATH
    - cp -R ./dingconnect-wp-plugin/* $DEPLOYPATH
